import "ress";
import { Inter } from "next/font/google";
import Header from "@/components/header/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    default: "Next.js Blog",
    template: "%s | Next.js Blog",
  },
  description: "Generated by create next app.",
};

export default function RootLayout({ children }) {
  return (
    <html lang='ja'>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
